package cz.mtrakal.myapplication

/**
 * https://github.com/harfbuzz/harfbuzz/issues/1104
 * The Georgian Extended Unicode Block (https://en.wikipedia.org/wiki/Georgian_Extended), used
 * for representing Georgian Mtavruli(capitalized Georgian glyphs) is not that widely adopted
 * yet, and not many fonts support it.To avoid rendering replacementGlyphs whenever we could be
 * rendering Georgian Mkhedruli (regular Georgian glyphs), we can detect the Mtavruli glyphs and
 * convert them to Mkhedruli.
 *
 * https://en.wikipedia.org/wiki/Georgian_(Unicode_block)
 * https://en.wikipedia.org/wiki/Georgian_scripts#Summary
 * https://unicode.org/L2/L2016/16034-n4707-georgian.pdf
 *
 * Created by mtrakal on 06.05.2020.
 */
object GeorgianUtil {
    /**
     * Not using codePoints and UCharacter, so it can have some side effects?
     */
    fun convertGeorgianUppercaseToLowercase(inputString: String?): String? {
        val sb = StringBuilder()
        inputString?.forEach { char ->
            sb.appendCodePoint(convertMtavruliToMkhedruli(char.toInt()))
        }
        return sb.toString()
    }

    private fun convertMtavruliToMkhedruli(char: Int): Int = conversionTable[char] ?: char

    private val conversionTable: HashMap<Int, Int> = hashMapOf(
        Pair(0x1C90, 0x10D0), // GEORGIAN MTAVRULI CAPITAL LETTER AN
        Pair(0x1C91, 0x10D1), // GEORGIAN MTAVRULI CAPITAL LETTER BAN
        Pair(0x1C92, 0x10D2), // GEORGIAN MTAVRULI CAPITAL LETTER GAN
        Pair(0x1C93, 0x10D3), // GEORGIAN MTAVRULI CAPITAL LETTER DON
        Pair(0x1C94, 0x10D4), // GEORGIAN MTAVRULI CAPITAL LETTER EN
        Pair(0x1C95, 0x10D5), // GEORGIAN MTAVRULI CAPITAL LETTER VIN
        Pair(0x1C96, 0x10D6), // GEORGIAN MTAVRULI CAPITAL LETTER ZEN
        Pair(0x1C97, 0x10D7), // GEORGIAN MTAVRULI CAPITAL LETTER TAN
        Pair(0x1C98, 0x10D8), // GEORGIAN MTAVRULI CAPITAL LETTER IN
        Pair(0x1C99, 0x10D9), // GEORGIAN MTAVRULI CAPITAL LETTER KAN
        Pair(0x1C9A, 0x10DA), // GEORGIAN MTAVRULI CAPITAL LETTER LAS
        Pair(0x1C9B, 0x10DB), // GEORGIAN MTAVRULI CAPITAL LETTER MAN
        Pair(0x1C9C, 0x10DC), // GEORGIAN MTAVRULI CAPITAL LETTER NAR
        Pair(0x1C9D, 0x10DD), // GEORGIAN MTAVRULI CAPITAL LETTER ON
        Pair(0x1C9E, 0x10DE), // GEORGIAN MTAVRULI CAPITAL LETTER PAR
        Pair(0x1C9F, 0x10DF), // GEORGIAN MTAVRULI CAPITAL LETTER ZHAR
        Pair(0x1CA0, 0x10E0), // GEORGIAN MTAVRULI CAPITAL LETTER RAE
        Pair(0x1CA1, 0x10E1), // GEORGIAN MTAVRULI CAPITAL LETTER SAN
        Pair(0x1CA2, 0x10E2), // GEORGIAN MTAVRULI CAPITAL LETTER TAR
        Pair(0x1CA3, 0x10E3), // GEORGIAN MTAVRULI CAPITAL LETTER UN
        Pair(0x1CA4, 0x10E4), // GEORGIAN MTAVRULI CAPITAL LETTER PHAR
        Pair(0x1CA5, 0x10E5), // GEORGIAN MTAVRULI CAPITAL LETTER KHAR
        Pair(0x1CA6, 0x10E6), // GEORGIAN MTAVRULI CAPITAL LETTER GHAN
        Pair(0x1CA7, 0x10E7), // GEORGIAN MTAVRULI CAPITAL LETTER QAR
        Pair(0x1CA8, 0x10E8), // GEORGIAN MTAVRULI CAPITAL LETTER SHIN
        Pair(0x1CA9, 0x10E9), // GEORGIAN MTAVRULI CAPITAL LETTER CHIN
        Pair(0x1CAA, 0x10EA), // GEORGIAN MTAVRULI CAPITAL LETTER CAN
        Pair(0x1CAB, 0x10EB), // GEORGIAN MTAVRULI CAPITAL LETTER JIL
        Pair(0x1CAC, 0x10EC), // GEORGIAN MTAVRULI CAPITAL LETTER CIL
        Pair(0x1CAD, 0x10ED), // GEORGIAN MTAVRULI CAPITAL LETTER CHAR
        Pair(0x1CAE, 0x10EE), // GEORGIAN MTAVRULI CAPITAL LETTER XAN
        Pair(0x1CAF, 0x10EF), // GEORGIAN MTAVRULI CAPITAL LETTER JHAN
        Pair(0x1CB0, 0x10F0), // GEORGIAN MTAVRULI CAPITAL LETTER HAE
        Pair(0x1CB1, 0x10F1), // GEORGIAN MTAVRULI CAPITAL LETTER HE
        Pair(0x1CB2, 0x10F2), // GEORGIAN MTAVRULI CAPITAL LETTER HIE
        Pair(0x1CB3, 0x10F3), // GEORGIAN MTAVRULI CAPITAL LETTER WE
        Pair(0x1CB4, 0x10F4), // GEORGIAN MTAVRULI CAPITAL LETTER HAR
        Pair(0x1CB5, 0x10F5), // GEORGIAN MTAVRULI CAPITAL LETTER HOE
        Pair(0x1CB6, 0x10F6), // GEORGIAN MTAVRULI CAPITAL LETTER FI
        Pair(0x1CB7, 0x10F7), // GEORGIAN MTAVRULI CAPITAL LETTER YN
        Pair(0x1CB8, 0x10F8), // GEORGIAN MTAVRULI CAPITAL LETTER ELIFI
        Pair(0x1CB9, 0x10F9), // GEORGIAN MTAVRULI CAPITAL LETTER TURNED GAN
        Pair(0x1CBA, 0x10FA), // GEORGIAN MTAVRULI CAPITAL LETTER AIN
        Pair(0x1CBD, 0x10FD), // GEORGIAN MTAVRULI CAPITAL LETTER AEN
        Pair(0x1CBE, 0x10FE), // GEORGIAN MTAVRULI CAPITAL LETTER HARD SIGN
        Pair(0x1CBF, 0x10FF) // GEORGIAN MTAVRULI CAPITAL LETTER LABIAL SIGN
    )

// Some next Georgian codes, should not be needed to convert
// (0x10D0, 0x1C90) //GEORGIAN LETTER AN / GEORGIAN SMALL LETTER AN
// (0x10D1, 0x1C91) //GEORGIAN LETTER BAN / GEORGIAN SMALL LETTER BAN
// (0x10D2, 0x1C92) //GEORGIAN LETTER GAN / GEORGIAN SMALL LETTER GAN
// (0x10D3, 0x1C93) //GEORGIAN LETTER DON / GEORGIAN SMALL LETTER DON
// (0x10D4, 0x1C94) //GEORGIAN LETTER EN / GEORGIAN SMALL LETTER EN
// (0x10D5, 0x1C95) //GEORGIAN LETTER VIN / GEORGIAN SMALL LETTER VIN
// (0x10D6, 0x1C96) //GEORGIAN LETTER ZEN / GEORGIAN SMALL LETTER ZEN
// (0x10D7, 0x1C97) //GEORGIAN LETTER TAN / GEORGIAN SMALL LETTER TAN
// (0x10D8, 0x1C98) //GEORGIAN LETTER IN / GEORGIAN SMALL LETTER IN
// (0x10D9, 0x1C99) //GEORGIAN LETTER KAN / GEORGIAN SMALL LETTER KAN
// (0x10DA, 0x1C9A) //GEORGIAN LETTER LAS / GEORGIAN SMALL LETTER LAS
// (0x10DB, 0x1C9B) //GEORGIAN LETTER MAN / GEORGIAN SMALL LETTER MAN
// (0x10DC, 0x1C9C) //GEORGIAN LETTER NAR / GEORGIAN SMALL LETTER NAR
// (0x10DD, 0x1C9D) //GEORGIAN LETTER ON / GEORGIAN SMALL LETTER ON
// (0x10DE, 0x1C9E) //GEORGIAN LETTER PAR / GEORGIAN SMALL LETTER PAR
// (0x10DF, 0x1C9F) //GEORGIAN LETTER ZHAR / GEORGIAN SMALL LETTER ZHAR
// (0x10E0, 0x1CA0) //GEORGIAN LETTER RAE / GEORGIAN SMALL LETTER RAE
// (0x10E1, 0x1CA1) //GEORGIAN LETTER SAN / GEORGIAN SMALL LETTER SAN
// (0x10E2, 0x1CA2) //GEORGIAN LETTER TAR / GEORGIAN SMALL LETTER TAR
// (0x10E3, 0x1CA3) //GEORGIAN LETTER UN / GEORGIAN SMALL LETTER UN
// (0x10E4, 0x1CA4) //GEORGIAN LETTER PHAR / GEORGIAN SMALL LETTER PHAR
// (0x10E5, 0x1CA5) //GEORGIAN LETTER KHAR / GEORGIAN SMALL LETTER KHAR
// (0x10E6, 0x1CA6) //GEORGIAN LETTER GHAN / GEORGIAN SMALL LETTER GHAN
// (0x10E7, 0x1CA7) //GEORGIAN LETTER QAR / GEORGIAN SMALL LETTER QAR
// (0x10E8, 0x1CA8) //GEORGIAN LETTER SHIN / GEORGIAN SMALL LETTER SHIN
// (0x10E9, 0x1CA9) //GEORGIAN LETTER CHIN / GEORGIAN SMALL LETTER CHIN
// (0x10EA, 0x1CAA) //GEORGIAN LETTER CAN / GEORGIAN SMALL LETTER CAN
// (0x10EB, 0x1CAB) //GEORGIAN LETTER JIL / GEORGIAN SMALL LETTER JIL
// (0x10EC, 0x1CAC) //GEORGIAN LETTER CIL / GEORGIAN SMALL LETTER CIL
// (0x10ED, 0x1CAD) //GEORGIAN LETTER CHAR / GEORGIAN SMALL LETTER CHAR
// (0x10EE, 0x1CAE) //GEORGIAN LETTER XAN / GEORGIAN SMALL LETTER XAN
// (0x10EF, 0x1CAF) //GEORGIAN LETTER JHAN / GEORGIAN SMALL LETTER JHAN
// (0x10F0, 0x1CB0) //GEORGIAN LETTER HAE / GEORGIAN SMALL LETTER HAE
// (0x10F1, 0x1CB1) //GEORGIAN LETTER HE / GEORGIAN SMALL LETTER HE
// (0x10F2, 0x1CB2) //GEORGIAN LETTER HIE / GEORGIAN SMALL LETTER HIE
// (0x10F3, 0x1CB3) //GEORGIAN LETTER WE / GEORGIAN SMALL LETTER WE
// (0x10F4, 0x1CB4) //GEORGIAN LETTER HAR / GEORGIAN SMALL LETTER HAR
// (0x10F5, 0x1CB5) //GEORGIAN LETTER HOE / GEORGIAN SMALL LETTER HOE
// (0x10F6, 0x1CB6) //GEORGIAN LETTER FI / GEORGIAN SMALL LETTER FI
// (0x10F7, 0x1CB7) //GEORGIAN LETTER YN /
// (0x10F8, 0x1CB8) //GEORGIAN LETTER ELIFI /
//
// (0x10F9, 0x1CB9) //GEORGIAN LETTER TURNED GAN
// (0x10FA, 0x1CBA) //GEORGIAN LETTER AIN
// (0x10FD, 0x1CBD) //GEORGIAN LETTER AEN
// (0x10FE, 0x1CBE) //GEORGIAN LETTER HARD SIGN
// (0x10FF, 0x1CBF) //GEORGIAN LETTER LABIAL SIGN
}
